version: "3"

services:
  test_app:
    build: .
    command: >
      sh -c "
             cd hashes_apps &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py test --noinput"
    volumes:
      - .:/app
    # env_file:
    #   - .env.test
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DB_USER=user001
      - POSTGRES_PASSWORD=123456789
      - DB_NAME=test_hash
      - DB_HOST=sample_project_test_hash_db_1
      - DB_PORT=5432
      - HASH_LENGTH=2
    ports:
      - 8000:8000
    depends_on:
      - test_hash_db

  test_hash_db:
    image: kartoza/postgis:11.5-2.5
    volumes:
      - test_postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=user001
      - POSTGRES_PASS=123456789
      - POSTGRES_DBNAME=test_hash
      - POSTGRES_HOST=localhost
    ports:
      - "5435:5432"

volumes:
  test_postgres_data:
