version: "3"

services:
  app:
    build: .
    command: >
      sh -c "python hashes_apps/manage.py wait_for_db &&
             python hashes_apps/manage.py migrate &&
             python hashes_apps/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - hash_db
  
  test_app:
    build: .
    command: >
      sh -c "
             cd hashes_apps &&
             python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py test --noinput"
    volumes:
      - .:/app
    env_file:
      - .env.test
    ports:
      - 8000:8000
    depends_on:
      - test_hash_db

  hash_db:
    image: kartoza/postgis:11.5-2.5
    volumes:
      # New storage location
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - "5435:5432"
  
  
  test_hash_db:
    image: kartoza/postgis:11.5-2.5
    volumes:
      # New storage location
      - test_postgres_data:/var/lib/postgresql
    env_file:
      - .env.test
    ports:
      - "5435:5432"

volumes:
  postgres_data:
  test_postgres_data:
